---
- name: Ensure Apache is stopped and disabled (Free up Port 80)
  service:
    name: httpd
    state: stopped
    enabled: no
  ignore_errors: yes  # In case httpd isn't even installed

- name: Install nginx
  dnf:
    name: nginx
    state: present

- name: Start nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
